#!/usr/bin/env python3
"""Regenerate every figure and table in the report from summary.csv.

Idempotent by construction: the only inputs are experiments/results/summary.csv
and session_manifest.json, and every output is overwritten in full. Running it
twice produces identical files, and running it after a partial sweep produces
figures for the rows that exist and a stated gap for the rest. No number in the
report is typed by hand.

Design notes on the figures, since the reasoning is not visible in the output:

  Form follows the data's job. Speedup against worker count is change over a
  continuous axis, so it is a line. Time per backend is a comparison of
  magnitudes across one categorical axis, so it is a bar in a single hue, not
  eight colours: the backend names are the identity channel and the length is
  the measurement. Efficiency against each device's own peak is two entities
  compared across sizes, so it is a grouped bar with two hues.

  At most three colour coded series appear in any one figure. The palette's
  first three slots are the ones that clear the separation floors with every
  pair visible at once, which is the case for a scatter or a chart a reader
  scans rather than follows. Line style and marker shape carry the same
  distinction again, so the figures survive greyscale printing and colour vision
  deficiency without depending on hue at all.

  No figure has two y axes. Where two quantities of different scale belong
  together they are either normalised to a common base or drawn as two panels.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt  # noqa: E402
import pandas as pd  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "experiments" / "results"
SUMMARY = RESULTS / "summary.csv"
MANIFEST = RESULTS / "session_manifest.json"
FIGURES = ROOT / "report" / "figures"
TABLES = ROOT / "report" / "tables"

# The reference palette, light surface. Only the first three categorical slots
# are used, because those are the ones validated with every pair visible at
# once; a fourth would put yellow beside orange and fail that gate.
SERIES = ["#2a78d6", "#eb6834", "#1baf7a"]
SEQUENTIAL = "#2a78d6"
INK = "#0b0b0b"
INK_SECONDARY = "#52514e"
MUTED = "#898781"
GRID = "#e1e0d9"
AXIS = "#c3c2b7"
SURFACE = "#fcfcfb"

# Secondary encoding, so identity never rests on hue alone.
MARKERS = ["o", "s", "^"]
DASHES = [(None, None), (5, 2), (1.5, 1.5)]

matplotlib.rcParams.update({
    "figure.facecolor": SURFACE,
    "axes.facecolor": SURFACE,
    "savefig.facecolor": SURFACE,
    "font.family": "sans-serif",
    "font.size": 9,
    "axes.labelsize": 9,
    "axes.titlesize": 10,
    "axes.titleweight": "normal",
    "axes.edgecolor": AXIS,
    "axes.labelcolor": INK,
    "axes.linewidth": 0.8,
    "axes.grid": True,
    "axes.axisbelow": True,
    "grid.color": GRID,
    "grid.linewidth": 0.6,
    "xtick.color": MUTED,
    "ytick.color": MUTED,
    "xtick.labelsize": 8,
    "ytick.labelsize": 8,
    "legend.frameon": False,
    "legend.fontsize": 8,
    "lines.linewidth": 1.6,
    "lines.markersize": 4.5,
    "figure.dpi": 150,
})


def style_axes(ax: Any) -> None:
    """Recessive chrome: no box, hairline grid, muted ticks."""
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(AXIS)
    ax.tick_params(length=3, width=0.8)


def save(fig: Any, name: str) -> None:
    FIGURES.mkdir(parents=True, exist_ok=True)
    path = FIGURES / name
    fig.savefig(path, bbox_inches="tight", pad_inches=0.02)
    plt.close(fig)
    print(f"  figure  {path.relative_to(ROOT)}")


def latex_escape(text: str) -> str:
    """Escape a value for LaTeX, and never emit a character the dash rule bans."""
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    out = "".join(replacements.get(char, char) for char in str(text))
    # A literal double hyphen would typeset as an en dash, which ground rule 1
    # forbids. This can only arise from data, never from the prose here.
    return out.replace("--", r"-{}-")


def write_table(name: str, header: list[str], rows: list[list[Any]], caption: str,
                label: str, column_spec: str | None = None) -> None:
    TABLES.mkdir(parents=True, exist_ok=True)
    spec = column_spec or ("l" + "r" * (len(header) - 1))
    lines = [
        "% Generated by scripts/gen_report_assets.py. Do not edit by hand.",
        r"\begin{table}[htbp]",
        r"\centering",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        rf"\begin{{tabular}}{{{spec}}}",
        r"\toprule",
        " & ".join(latex_escape(h) for h in header) + r" \\",
        r"\midrule",
    ]
    for row in rows:
        lines.append(" & ".join(latex_escape(value) for value in row) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    path = TABLES / name
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  table   {path.relative_to(ROOT)}")


def fmt(value: Any, places: int = 3) -> str:
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return "pending"
    if isinstance(value, float):
        if value != 0 and (abs(value) < 1e-3 or abs(value) >= 1e6):
            return f"{value:.{places}e}"
        return f"{value:.{places}f}"
    return str(value)


# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------

def figure_scaling(data: pd.DataFrame) -> dict[str, Any]:
    """Speedup against worker count, and the knee where fast cores run out."""
    block = data[(data["label"] == "scaling") & (data["solver"] == "jacobi")]
    if block.empty:
        return {}

    fig, ax = plt.subplots(figsize=(5.4, 3.4))
    backends = [b for b in ("openmp", "pthreads", "jthread") if b in set(block["backend"])]
    knees: dict[str, Any] = {}

    for index, backend in enumerate(backends):
        series = block[block["backend"] == backend].sort_values("workers")
        if series.empty:
            continue
        baseline = series[series["workers"] == 1]["seconds_median"]
        if baseline.empty:
            continue
        base = float(baseline.iloc[0])
        speedup = base / series["seconds_median"].astype(float)
        ax.plot(series["workers"], speedup,
                color=SERIES[index], marker=MARKERS[index],
                dashes=DASHES[index] if DASHES[index][0] else (None, None),
                label=backend, markeredgecolor=SURFACE, markeredgewidth=0.6)
        knees[backend] = find_knee(series["workers"].tolist(), speedup.tolist())

    # Ideal scaling is reference chrome, not a series, so it is muted and unmarked.
    top = int(block["workers"].max())
    ax.plot([1, top], [1, top], color=MUTED, linewidth=0.9, dashes=(2, 3), zorder=0)
    ax.annotate("ideal", xy=(top * 0.62, top * 0.66), color=MUTED, fontsize=8)

    ax.set_xlabel("workers")
    ax.set_ylabel("speedup against one worker")
    ax.set_title("Jacobi sweep scaling, 1023 by 1023 grid", color=INK, loc="left")
    ax.legend(loc="upper left")
    style_axes(ax)
    save(fig, "scaling_speedup.pdf")
    return knees


def find_knee(workers: list[float], speedup: list[float]) -> dict[str, Any]:
    """Locate the change of slope by the best two segment least squares split.

    The guest cannot label its processors as performance or efficiency cores
    (ENV-04), so the knee is read from the aggregate curve, which depends only
    on how many cores are engaged. The split minimising total residual is the
    worker count past which adding workers buys measurably less.
    """
    if len(workers) < 5:
        return {}
    best = None
    for cut in range(2, len(workers) - 2):
        left = fit_line(workers[:cut + 1], speedup[:cut + 1])
        right = fit_line(workers[cut:], speedup[cut:])
        total = left["residual"] + right["residual"]
        if best is None or total < best["residual"]:
            best = {
                "workers": workers[cut],
                "residual": total,
                "slope_before": left["slope"],
                "slope_after": right["slope"],
            }
    return best or {}


def fit_line(xs: list[float], ys: list[float]) -> dict[str, float]:
    n = len(xs)
    if n < 2:
        return {"slope": 0.0, "residual": 0.0}
    mean_x = sum(xs) / n
    mean_y = sum(ys) / n
    sxx = sum((x - mean_x) ** 2 for x in xs)
    sxy = sum((x - mean_x) * (y - mean_y) for x, y in zip(xs, ys))
    slope = sxy / sxx if sxx else 0.0
    intercept = mean_y - slope * mean_x
    residual = sum((y - (slope * x + intercept)) ** 2 for x, y in zip(xs, ys))
    return {"slope": slope, "residual": residual}


def figure_backend_cost(data: pd.DataFrame) -> None:
    """Time per backend on identical work: one categorical axis, one hue."""
    block = data[(data["label"] == "backend_cost") & (data["solver"] == "jacobi")]
    if block.empty:
        return
    size = sorted(block["unknowns"].unique())[-1]
    block = block[block["unknowns"] == size].sort_values("seconds_median")
    if block.empty:
        return

    fig, ax = plt.subplots(figsize=(5.4, 2.9))
    names = block["backend"].tolist()
    times = block["seconds_median"].astype(float).tolist()
    positions = range(len(names))
    # Magnitude on one categorical axis: a single hue, length carries the value.
    ax.barh(list(positions), times, color=SEQUENTIAL, height=0.62)
    ax.set_yticks(list(positions), names)
    ax.invert_yaxis()
    ax.set_xlabel("seconds, median of 5")
    ax.set_title(f"200 Jacobi sweeps at {int(size):,} unknowns, 20 workers",
                 color=INK, loc="left")
    # Direct labels rather than a value on every gridline.
    for position, value in zip(positions, times):
        ax.annotate(f"{value:.3f}", xy=(value, position), xytext=(4, 0),
                    textcoords="offset points", va="center", fontsize=8,
                    color=INK_SECONDARY)
    ax.set_xlim(0, max(times) * 1.18)
    ax.grid(axis="y", visible=False)
    style_axes(ax)
    save(fig, "backend_cost.pdf")


def figure_device_efficiency(data: pd.DataFrame, bandwidth: dict[str, Any]) -> None:
    """Percent of each device's own measured triad bandwidth.

    This is the fair comparison of Section 8.3: a dimensionless ratio that says
    how well each device is being used, rather than which device is faster.
    """
    block = data[data["label"] == "device_comparison"]
    if block.empty:
        return
    host_peak = (bandwidth.get("host") or {}).get("gib_per_second")
    device_peak = (bandwidth.get("gpu") or {}).get("gib_per_second")
    if not host_peak or not device_peak:
        return

    solver = "jacobi"
    cpu = block[(block["backend"] == "openmp") & (block["solver"] == solver)]
    gpu = block[(block["backend"] == "cuda") & (block["solver"] == solver)]
    # Only sizes where both devices are genuinely streaming. Below its cache a
    # device is not bandwidth bound and the ratio would exceed one, which would
    # be an artefact of the roofline assumption rather than a measurement.
    sizes = [
        s for s in sorted(set(cpu["unknowns"]) & set(gpu["unknowns"]))
        if working_set_mib(float(s)) > STREAMING_MARGIN * max(CACHE_MIB.values())
    ]
    if not sizes:
        return

    cpu_efficiency = [
        float(cpu[cpu["unknowns"] == s]["gib_per_second"].iloc[0]) / host_peak * 100
        for s in sizes
    ]
    gpu_efficiency = [
        float(gpu[gpu["unknowns"] == s]["gib_per_second"].iloc[0]) / device_peak * 100
        for s in sizes
    ]

    fig, ax = plt.subplots(figsize=(5.4, 3.0))
    width = 0.36
    positions = list(range(len(sizes)))
    left = [p - width / 2 - 0.01 for p in positions]
    right = [p + width / 2 + 0.01 for p in positions]
    ax.bar(left, cpu_efficiency, width, color=SERIES[0], label="host, 20 threads")
    ax.bar(right, gpu_efficiency, width, color=SERIES[1], label="RTX 5070")

    for xs, values in ((left, cpu_efficiency), (right, gpu_efficiency)):
        for x, value in zip(xs, values):
            ax.annotate(f"{value:.0f}%", xy=(x, value), xytext=(0, 3),
                        textcoords="offset points", ha="center", fontsize=8,
                        color=INK_SECONDARY)

    ax.set_xticks(positions, [f"{int(s):,}" for s in sizes])
    ax.set_xlabel("unknowns")
    ax.set_ylabel("percent of own measured peak")
    ax.set_title("Jacobi sweep efficiency against each device's own bandwidth",
                 color=INK, loc="left")
    ax.set_ylim(0, max(cpu_efficiency + gpu_efficiency) * 1.25)
    ax.legend(loc="upper left")
    ax.grid(axis="x", visible=False)
    style_axes(ax)
    save(fig, "device_efficiency.pdf")


def figure_iteration_counts(data: pd.DataFrame) -> None:
    """Iterations to tolerance per method: hardware free, and reported first."""
    block = data[data["label"] == "convergence_counts"]
    if block.empty:
        return
    size = sorted(block["unknowns"].unique())[-1]
    block = block[(block["unknowns"] == size) & (block["converged"] == 1)]
    block = block.sort_values("iterations", ascending=False)
    if block.empty:
        return

    fig, ax = plt.subplots(figsize=(5.4, 3.8))
    names = block["solver"].tolist()
    counts = block["iterations"].astype(float).tolist()
    positions = list(range(len(names)))
    ax.barh(positions, counts, color=SEQUENTIAL, height=0.66)
    ax.set_yticks(positions, names)
    ax.set_xscale("log")
    ax.set_xlabel("iterations to relative residual 1e-8, log scale")
    side = int(round(float(size) ** 0.5))
    ax.set_title(f"Iterations to tolerance, {side} by {side} grid", color=INK, loc="left")
    for position, value in zip(positions, counts):
        ax.annotate(f"{int(value):,}", xy=(value, position), xytext=(4, 0),
                    textcoords="offset points", va="center", fontsize=8,
                    color=INK_SECONDARY)
    ax.grid(axis="y", visible=False)
    style_axes(ax)
    save(fig, "iteration_counts.pdf")


def figure_convergence_growth(data: pd.DataFrame) -> None:
    """Iteration count against grid size: the change in growth order, measured."""
    block = data[data["label"].isin(["convergence_counts", "convergence_counts_large"])]
    block = block[block["converged"] == 1]
    if block.empty:
        return

    chosen = [s for s in ("jacobi", "gauss_seidel_f", "cg") if s in set(block["solver"])]
    if not chosen:
        return

    fig, ax = plt.subplots(figsize=(5.4, 3.4))
    for index, solver in enumerate(chosen):
        series = block[block["solver"] == solver].sort_values("unknowns")
        if series.empty:
            continue
        sides = [round(float(u) ** 0.5) for u in series["unknowns"]]
        ax.plot(sides, series["iterations"].astype(float),
                color=SERIES[index], marker=MARKERS[index],
                dashes=DASHES[index] if DASHES[index][0] else (None, None),
                label=solver, markeredgecolor=SURFACE, markeredgewidth=0.6)

    ax.set_xscale("log", base=2)
    ax.set_yscale("log")
    ax.set_xlabel("grid points per side")
    ax.set_ylabel("iterations to 1e-8, log scale")
    ax.set_title("Iteration count growth with grid size", color=INK, loc="left")
    ax.legend(loc="upper left")
    style_axes(ax)
    save(fig, "convergence_growth.pdf")


def figure_mpi_communication(data: pd.DataFrame) -> None:
    """How MPI scales, and where conjugate gradient loses to Jacobi."""
    block = data[(data["label"] == "mpi_scaling") & (data["backend"] == "mpi")]
    if block.empty:
        return
    chosen = [s for s in ("jacobi", "cg", "gauss_seidel_f") if s in set(block["solver"])]
    if not chosen:
        return

    fig, ax = plt.subplots(figsize=(5.4, 3.4))
    for index, solver in enumerate(chosen[:3]):
        series = block[block["solver"] == solver].sort_values("workers")
        baseline = series[series["workers"] == 1]["seconds_median"]
        if baseline.empty:
            continue
        base = float(baseline.iloc[0])
        speedup = base / series["seconds_median"].astype(float)
        ax.plot(series["workers"], speedup,
                color=SERIES[index], marker=MARKERS[index],
                dashes=DASHES[index] if DASHES[index][0] else (None, None),
                label=solver, markeredgecolor=SURFACE, markeredgewidth=0.6)

    top = int(block["workers"].max())
    ax.plot([1, top], [1, top], color=MUTED, linewidth=0.9, dashes=(2, 3), zorder=0)
    ax.annotate("ideal", xy=(top * 0.62, top * 0.66), color=MUTED, fontsize=8)
    ax.set_xlabel("ranks")
    ax.set_ylabel("speedup against one rank")
    ax.set_title("MPI scaling by method, 1023 by 1023 grid", color=INK, loc="left")
    ax.legend(loc="upper left")
    style_axes(ax)
    save(fig, "mpi_scaling.pdf")


# ---------------------------------------------------------------------------
# Tables
# ---------------------------------------------------------------------------

def table_convergence(data: pd.DataFrame) -> None:
    block = data[data["label"] == "convergence_counts"]
    if block.empty:
        return
    sizes = sorted(block["unknowns"].unique())
    solvers = list(dict.fromkeys(block["solver"]))
    header = ["method"] + [f"{int(round(float(s) ** 0.5))} by {int(round(float(s) ** 0.5))}"
                           for s in sizes]
    rows: list[list[Any]] = []
    for solver in solvers:
        row: list[Any] = [solver]
        for size in sizes:
            match = block[(block["solver"] == solver) & (block["unknowns"] == size)]
            if match.empty:
                row.append("pending")
            elif int(match["converged"].iloc[0]) == 0:
                row.append("cap")
            else:
                row.append(f"{int(match['iterations'].iloc[0]):,}")
        rows.append(row)
    write_table(
        "convergence.tex", header, rows,
        "Iterations to a relative residual of 1e-8 on the 2D Poisson problem with a "
        "spectrally rich source. These counts are properties of the mathematics and "
        "carry to any machine, which is why Section 8.3 reports them before any timing.",
        "tab:convergence",
    )


def table_backend_cost(data: pd.DataFrame) -> None:
    block = data[data["label"] == "backend_cost"]
    if block.empty:
        return
    size = sorted(block["unknowns"].unique())[-1]
    block = block[block["unknowns"] == size]
    backends = list(dict.fromkeys(block["backend"]))
    solvers = list(dict.fromkeys(block["solver"]))
    header = ["backend"] + solvers
    rows: list[list[Any]] = []
    for backend in backends:
        row: list[Any] = [backend]
        for solver in solvers:
            match = block[(block["backend"] == backend) & (block["solver"] == solver)]
            row.append(fmt(float(match["seconds_median"].iloc[0])) if not match.empty
                       else "pending")
        rows.append(row)
    write_table(
        "backend_cost.tex", header, rows,
        f"Seconds for a fixed sweep count at {int(size):,} unknowns with 20 workers, "
        "median of five repetitions. Every backend performs bit identical arithmetic, "
        "so the only variable is the execution model.",
        "tab:backend-cost",
    )


# Last level cache of each device, in MiB. The working set of a sweep is
# compared against these so a ratio computed under the streaming assumption is
# never presented as a DRAM efficiency when the problem in fact fits in cache.
# The RTX 5070 figure is its L2; the host figure is the L3 reported by sysfs.
CACHE_MIB = {"host": 33.0, "gpu": 48.0}

# How many times the last level cache the working set must exceed before a
# streaming efficiency is quoted. A working set merely larger than the cache is
# not enough: at twice the cache a good fraction of the traffic is still served
# from it, and the ratio comes out above one, which is the model announcing that
# it does not apply rather than a result. Four times is where the measured
# ratios settle below one and stay there.
STREAMING_MARGIN = 4.0


def working_set_mib(unknowns: float, vectors: int = 3) -> float:
    """Bytes a sweep touches, in MiB: the iterate, the previous iterate and the
    right hand side."""
    return unknowns * vectors * 8.0 / (1024.0 * 1024.0)


def cache_regime(mib: float, cache: float) -> str:
    """Which regime a working set is in: streaming, partly cached, or resident."""
    if mib < cache:
        return "resident"
    if mib < STREAMING_MARGIN * cache:
        return "partial"
    return "streaming"


def table_device_comparison(data: pd.DataFrame, bandwidth: dict[str, Any]) -> None:
    block = data[data["label"] == "device_comparison"]
    if block.empty:
        return
    host_peak = (bandwidth.get("host") or {}).get("gib_per_second")
    device_peak = (bandwidth.get("gpu") or {}).get("gib_per_second")

    header = ["method", "unknowns", "device", "working set", "GiB/s",
              "percent of own peak", "seconds"]
    rows: list[list[Any]] = []
    cache_bound_seen = False
    for solver in dict.fromkeys(block["solver"]):
        for size in sorted(block["unknowns"].unique()):
            for backend, peak, name, cache in (
                ("openmp", host_peak, "host, 20 threads", CACHE_MIB["host"]),
                ("cuda", device_peak, "RTX 5070", CACHE_MIB["gpu"]),
            ):
                match = block[(block["solver"] == solver) & (block["unknowns"] == size) &
                              (block["backend"] == backend)]
                if match.empty:
                    continue
                achieved = float(match["gib_per_second"].iloc[0])
                mib = working_set_mib(float(size))
                # A working set that is not comfortably larger than the last
                # level cache means the sweep is not purely streaming from
                # memory, so the ratio is not a DRAM efficiency and must not be
                # presented as one.
                regime = cache_regime(mib, cache)
                if regime != "streaming":
                    cache_bound_seen = True
                if regime == "resident":
                    efficiency = "cache resident"
                elif regime == "partial":
                    efficiency = "partly cached"
                else:
                    efficiency = f"{achieved / peak * 100:.1f}" if peak else "pending"
                rows.append([solver, f"{int(size):,}", name, f"{mib:.0f} MiB",
                             f"{achieved:.1f}", efficiency,
                             fmt(float(match["seconds_median"].iloc[0]))])

    caption = (
        "Achieved bandwidth, efficiency against each device's own measured STREAM triad, "
        "and absolute time. The efficiency column is the comparable one: it is "
        "dimensionless and says how well each device is used. The seconds column is a "
        "property of this particular pair of devices and of nothing else."
    )
    if cache_bound_seen:
        caption += (
            " A streaming efficiency is quoted only where the working set exceeds that "
            "device's last level cache by a factor of four. Rows marked cache resident "
            "have a working set smaller than the cache and rows marked partly cached "
            "have one within that factor; in both cases a good share of the traffic never "
            "reaches memory, so the sweep runs faster than the memory system alone would "
            "allow and a percentage would exceed one hundred. That would be the roofline "
            "assumption announcing that it does not apply, not a result. The comparison "
            "should therefore be read from the largest size, where both devices are "
            "unambiguously bandwidth bound."
        )
    write_table("device_comparison.tex", header, rows, caption, "tab:device-comparison",
                column_spec="llrrrrr")


def table_bandwidth(bandwidth: dict[str, Any]) -> None:
    rows = []
    for key, label in (("host", "host, all threads"), ("gpu", "RTX 5070")):
        entry = bandwidth.get(key) or {}
        value = entry.get("gib_per_second")
        rows.append([label, fmt(value, 1) if value else "pending",
                     entry.get("detail", "").strip()])
    write_table(
        "bandwidth.tex", ["device", "GiB/s", "measurement"], rows,
        "Measured STREAM triad bandwidth. Every efficiency figure in this report "
        "divides by these values, which were measured on this machine, and never by a "
        "manufacturer's specification.",
        "tab:bandwidth",
        column_spec="lrp{0.5\\textwidth}",
    )


def table_reduction_cost(data: pd.DataFrame) -> None:
    block = data[data["label"] == "reduction_cost"]
    if block.empty:
        return
    backends = list(dict.fromkeys(block["backend"]))
    rows: list[list[Any]] = []
    for backend in backends:
        deterministic = block[(block["backend"] == backend) &
                              (block["reduction"] == "deterministic")]
        native = block[(block["backend"] == backend) & (block["reduction"] == "native")]
        if deterministic.empty or native.empty:
            continue
        d = float(deterministic["seconds_median"].iloc[0])
        n = float(native["seconds_median"].iloc[0])
        overhead = (d / n - 1.0) * 100 if n else 0.0
        rows.append([backend, fmt(d), fmt(n), f"{overhead:+.1f}"])
    write_table(
        "reduction_cost.tex",
        ["backend", "deterministic (s)", "native (s)", "overhead (percent)"], rows,
        "The price of reproducibility. The deterministic mode combines partial sums in a "
        "fixed order that does not depend on the worker count, which is what lets the "
        "equivalence suite assert bit identical results; the native mode uses the "
        "model's own reduction. Conjugate gradient is used because its two global "
        "reductions per iteration make it the method most exposed to the difference.",
        "tab:reduction-cost",
    )


def table_pinning(data: pd.DataFrame) -> None:
    block = data[data["label"] == "pinning"]
    if block.empty:
        return
    policies = list(dict.fromkeys(block["pinning"]))
    backends = list(dict.fromkeys(block["backend"]))
    workers = sorted(block["workers"].unique())
    header = ["backend", "workers"] + policies
    rows: list[list[Any]] = []
    for backend in backends:
        for worker_count in workers:
            row: list[Any] = [backend, str(int(worker_count))]
            for policy in policies:
                match = block[(block["backend"] == backend) &
                              (block["workers"] == worker_count) &
                              (block["pinning"] == policy)]
                row.append(fmt(float(match["seconds_median"].iloc[0])) if not match.empty
                           else "pending")
            rows.append(row)
    write_table(
        "pinning.tex", header, rows,
        "Seconds by thread binding policy. Under WSL2 an affinity request binds a thread "
        "to a guest virtual processor and the hypervisor remains free to place that "
        "processor on any host core, so the expectation here is a smaller effect than the "
        "same experiment would show on bare metal.",
        "tab:pinning",
    )


def table_schedule(data: pd.DataFrame) -> None:
    block = data[data["label"] == "schedule_cost"]
    if block.empty:
        return
    rows: list[list[Any]] = []
    for backend in dict.fromkeys(block["backend"]):
        static = block[(block["backend"] == backend) & (block["schedule"] == "static")]
        dynamic = block[(block["backend"] == backend) & (block["schedule"] == "dynamic")]
        if static.empty or dynamic.empty:
            continue
        s = float(static["seconds_median"].iloc[0])
        d = float(dynamic["seconds_median"].iloc[0])
        rows.append([backend, fmt(s), fmt(d), f"{(d / s - 1.0) * 100:+.1f}"])
    write_table(
        "schedule_cost.tex",
        ["backend", "static (s)", "dynamic (s)", "dynamic overhead (percent)"], rows,
        "What a dynamic schedule costs on uniform work. This is the measurement behind "
        "leaving work stealing out of the jthread pool: on a balanced stencil sweep the "
        "extra bookkeeping buys nothing.",
        "tab:schedule-cost",
    )


def table_knee(knees: dict[str, Any]) -> None:
    if not knees:
        return
    rows = [
        [backend, str(int(knee.get("workers", 0))),
         fmt(knee.get("slope_before"), 2), fmt(knee.get("slope_after"), 2)]
        for backend, knee in knees.items() if knee
    ]
    if not rows:
        return
    write_table(
        "knee.tex",
        ["backend", "knee at workers", "speedup per worker before", "after"], rows,
        "The knee in the scaling curve, found as the two segment split that minimises "
        "total least squares residual. The guest cannot identify which logical processors "
        "are performance cores, so this is read from the aggregate curve, which depends "
        "only on how many cores are engaged and is therefore valid under virtualisation.",
        "tab:knee",
    )


def main() -> int:
    if not SUMMARY.exists():
        print(f"gen_report_assets: {SUMMARY} not found. Run make sweep first.",
              file=sys.stderr)
        return 2

    data = pd.read_csv(SUMMARY)
    for column in ("unknowns", "workers", "iterations", "converged", "seconds_median",
                   "gib_per_second", "updates_per_second"):
        if column in data.columns:
            data[column] = pd.to_numeric(data[column], errors="coerce")
    data["label"] = data["label"].fillna("").astype(str).str.split().str[0]

    bandwidth: dict[str, Any] = {}
    if MANIFEST.exists():
        bandwidth = json.loads(MANIFEST.read_text(encoding="utf-8")).get("bandwidth", {})

    print(f"gen_report_assets: {len(data)} rows from {SUMMARY.relative_to(ROOT)}")
    FIGURES.mkdir(parents=True, exist_ok=True)
    TABLES.mkdir(parents=True, exist_ok=True)

    knees = figure_scaling(data)
    figure_backend_cost(data)
    figure_device_efficiency(data, bandwidth)
    figure_iteration_counts(data)
    figure_convergence_growth(data)
    figure_mpi_communication(data)

    table_convergence(data)
    table_backend_cost(data)
    table_device_comparison(data, bandwidth)
    table_bandwidth(bandwidth)
    table_reduction_cost(data)
    table_pinning(data)
    table_schedule(data)
    table_knee(knees)

    print("gen_report_assets: done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
