// SPDX-License-Identifier: MIT
/// \file test_version.cpp
/// The generated version header says the same thing twice, and this asserts the
/// two spellings agree.
///
/// `pnl/version.hpp` is generated by CMake from `project()`, so the three
/// integers and the string come from one source and cannot drift by hand. What
/// can go wrong is the substitution itself: a template edited so that a macro
/// stops being expanded leaves a header that still compiles, still defines every
/// name, and reports a version nobody set. A comparison of the two spellings is
/// the cheapest thing that fails when that happens.

#include <pnl/version.hpp>

#include <cstdio>
#include <pnl_test.hpp>
#include <string_view>

PNL_TEST("version/the integer triple spells the version string") {
    char spelled[64];
    const int written = std::snprintf(spelled,
                                      sizeof spelled,
                                      "%d.%d.%d",
                                      pnl::VERSION.major_version,
                                      pnl::VERSION.minor_version,
                                      pnl::VERSION.patch_version);
    PNL_REQUIRE(written > 0 && written < static_cast<int>(sizeof spelled));
    PNL_REQUIRE_MESSAGE(std::string_view(spelled) == std::string_view(pnl::VERSION_STRING),
                        "the version integers and the version string disagree");
}

PNL_TEST("version/the macro and the constant carry the same string") {
    PNL_REQUIRE(std::string_view(PNL_VERSION_STRING) == std::string_view(pnl::VERSION_STRING));
    PNL_REQUIRE(PNL_VERSION_MAJOR == pnl::VERSION.major_version);
    PNL_REQUIRE(PNL_VERSION_MINOR == pnl::VERSION.minor_version);
    PNL_REQUIRE(PNL_VERSION_PATCH == pnl::VERSION.patch_version);
}
